# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Rang Liu"
description              : "Postdoc"
repository               : "RangLiu0706/RangLiu0706.github.io"

# google analytics
google_analytics_id      :  324368529 # get google_analytics_id from https://analytics.google.com/analytics/

# SEO Related (uncomment and fill in when needed)
# google_site_verification :
# bing_site_verification   :
# baidu_site_verification  :

# Site Author
author:
  name             : "Rang Liu"
  avatar           : "images/Rang.jpg"
  bio              : "University of California Irvine"
  location         : "Irvine, CA"
  googlescholar    : "https://scholar.google.com/citations?user=YVZWuQcAAAAJ&hl=en"
  email            : "rangl2@uci.edu"
  researchgate     : "https://www.researchgate.net/profile/Rang-Liu-3"


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
